general:
   check_for_updates: true
   update_check_interval: 180
# Database settings
database:
   url: 'jdbc:mysql://localhost:3306/'
   database: 'database'
   user: 'username'
   password: 'password'
   table_pvp_top: dspvptop_kills
messages:
  menu_header: '&8~~=={ &e&ldsPvptop &r&8}==~~'
  menu_killdeath: ' &e/pvptop [killdeath|kd] [start]'
  menu_kills: ' &e/pvptop [kills|k] [start]'
  menu_deaths: ' &e/pvptop [deaths|d] [start]'
  killdeath_header: '&8=========={ &e&ldsPvptop kill/death rate&r&8}=========='
  kills_header: '&8=========={ &e&ldsPvptop kills&r&8}=========='
  deaths_header: '&8=========={ &e&ldsPvptop deaths&r&8=========='
  killdeath_line: '<rank> -  &e<player>&f - <killdeath> &7(<kills> kills, <deaths> deaths)'
  kills_line: '<rank> -  &e<player>&f - <kills> kills &7(<deaths> deaths, <killdeath> k/d)'
  deaths_line: '<rank> -  &e<player>&f - <deaths> deaths &7(<kills> kills, <killdeath> k/d)'
  error_sql_exception: '&cSomething went wrong! Please contact an admin'
# Permissions to give to players
permission:
  # kills contains all the permissions someone gets when he/she has more or the same
  # amount of kills as put in front of the : character. Format: <numberOfKills>: <permission>
  # IMPORTANT The number needs to be put between quotes (example: '100')
  kills:
    # example config down here
    #'50': title.pvp50
    #'100': title.pvp100
    #'200': title.pvp200