# ==== Config of dsPvptop ====
# For more info and explanation, go to
# https://github.com/denniss17/dsPvptop/blob/master/dsPvptop/config.yml
general:
   # Should the plugin check for updates automaticly?
   check_for_updates: true
   # Time in minutes between two update checks
   update_check_interval: 180
   # How should the kills and deaths be saved? Possible values: 'database'
   # 'yml is not added yet!'
   save_method: database
   # Is the killstreak broadcast enabled?
   # Killstreak broadcast is something like this:
   # "Player abc has a killstreak of 6! Stop it!"
   killstreak_broadcast_enabled: true
   # Starting from which killstreak is this broadcasted?
   killstreak_broadcast_start: 5
# Database settings
database:
   # URL of the database
   url: 'jdbc:mysql://localhost:3306/'
   database: 'database'
   user: 'username'
   password: 'password'
   # The table in which to store kills and deaths
   table_pvp_top: dspvptop
messages: 
   # The menu when somebody uses only /pvptop
   menu_header: '&8~~=={ &e&ldsPvPtop &r&8}==~~'
   menu_killdeath: ' &e/pvptop killdeath|kd [start] &rShow kill/death top'
   menu_kills: ' &e/pvptop kills|k [start] &rShow killtop'
   menu_deaths: ' &e/pvptop deaths|d [start] &rShow deathtop'
   menu_killstreak: ' &e/pvptop killstreak|ks [start] &rShow killstreaktop'
   menu_me: ' &e/pvptop me &rShow your stats'
   menu_reload: ' &e/pvptop reload &rReload config and permissions'
   # The markup for the headers of the different tops
   killdeath_header: '&8=========={ &e&ldsPvPtop kill/death rate&r &8}=========='
   kills_header: '&8=========={ &e&ldsPvPtop kills&r &8}=========='
   deaths_header: '&8=========={ &e&ldsPvPtop deaths&r &8}=========='
   killstreak_header: '&8=========={ &e&ldsPvPtop killstreaks&r &8}=========='
   # The format of a single lines for the different tops
   # Possible tags: 
   # <rank> The rank of this player in this top
   # <player> The name of the player
   # <killdeath> The kill/death-rate of this player
   # <kills> The number of kills of this player
   # <deaths> The number of deaths of this player
   # <killstreak> The maximum killstreak this player ever had
   # <curstreak> The current killstreak of this player
   killdeath_line: '<rank> -  &e<player>&f - <killdeath> &7(<kills> kills, <deaths> deaths)'
   kills_line: '<rank> -  &e<player>&f - <kills> kills &7(<deaths> deaths, <killdeath> k/d)'
   deaths_line: '<rank> -  &e<player>&f - <deaths> deaths &7(<kills> kills, <killdeath> k/d)'
   killstreak_line: '<rank> -  &e<player>&f - <killstreak> killstreak &7(Current: <curstreak>)'
   # The format of the message you get when calling /pvptop me
   me_line: 'Your stats: &e<kills> &fkills - &e<deaths> &fdeaths - &e<killdeath> &fkill/death'
   # The format of the killstreak broadcast
   killstreak_broadcast: '&8[&ePvPtop&8] &e<player> &fhas a killstreak of &e<curstreak>&f! Stop it!'
   # The message a player gets when for example calling /pvptop kd while
   # an io failure occured (SQL offline, couldn`t read from file etc)
   error_io_failure: '&8[&ePvPtop&8] &cSomething went wrong! Please contact an admin'
   error_no_permission: '&8[&ePvPtop&8] &cYou have no permission to do this!'
   reloaded: '&8[&ePvPtop&8] &fConfig and permissions reloaded'
   update_notification: '&8[&ePvPtop&8] &eThere is a new version (&f{version}&e, current: &f{current}&e) available. Download it here: {website}'
# Permissions to give to players
permission:
  # Permissions to give to players if the given condition is met
  # Format: '<condition>': permission
  # Possible conditions:
  # '>10' or '10'  - The permission is given if you have more than ten kills, deaths etc.
  # '<10'          - The permission is given if you have less than ten kills, deaths etc.
  # Floats are also possible, but use a comma (',') as divider (so '2,5' instead of '2.5').
  # IMPORTANT The condition needs to be put between quotes (example: '100')
  # Example config:
  # kills:
  #    '>100': title.pvp100   # Granted if more than 100 kills
  # killdeath:
  #    '2,5': worldguard.elitepvpman   # Granted if kill/death rate is higher than 2.5
  # deaths:
  #    '<5': regions.hospital    # Granted if you have less then 5 deaths
  # killstreak:
  #    '>10': title.owner      # Granted if the player ever had a killstreak higher than 10
  # currentkillstreak:
  #    '>5': title.unstopable      # Granted if the player currently has a killstreak higher than 5