name: dsPvptop
main: denniss17.dsPvptop.DS_Pvptop
version: 1.0.0
author: Denniss17
description: This plugins adds pvptop.
commands:
   pvptop:
      description: Shows the pvp top
      usage: /<command> <start>
      permission: ds_pvptop.pvptop
permissions:
   ds_pvptop.admin:
      description: Access to all commands
      default: op
      children:
         dspvptop.player: true
   ds_pvptop.player:
      description: Permission to use /pvptop
      default: true